# Generated by Django 2.2.1 on 2019-10-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Pod',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
